---
# This playbook copies over the app code run by the node.js/express servers.
# It also installs the production node modules specified in package.json.
# It is used by both the initial deployment playbook (site.yml) and in rolling
# upgrades of app code.

- name: Copy over the dist folder
  # Because we are copying from the wynno-gateway server, the necessary config keys
  # are present there and so will be copied over in this step too
  synchronize: src=../../../../../dist dest=/home/deploy/wynno delete=yes

- name: Install node modules used in production locally
  npm: path=/home/deploy/wynno/dist production=yes

- name: Make the www-data user the owner of the New Relic log file
  # The previous task installed the New Relic node module
  # Since we run our server as the www-data user, that user needs to be able to write
  # to the newrelic_agent.log file
  shell: chown www-data:www-data /home/deploy/wynno/dist/newrelic_agent.log
  sudo: yes
