---
# This playbook is executed on all wynno node.js webservers.

- name: Ensure system packages necessary for node modules particularly zerorpc are installed
  apt: pkg={{ item }} state=present update_cache=yes
  sudo: yes
  with_items:
    - python-software-properties
    - make
    - build-essential
    - libzmq-dev
    - libevent-dev

# We install a particular version of node using the package manager
# We don't need to use nvm to install node, because we aren't going to be working
# with multiple versions of node
# because this is a production environment. We can still upgrade node via the apt
# package manager as necessary.
# (nvm was making things difficult in our Upstart script because we had to run nvm.sh
# in every shell just so that the paths worked)
- name: Add node.js PPA
  apt_repository: repo='ppa:chris-lea/node.js'
  sudo: yes

- name: Install node.js
  apt: pkg=nodejs=0.10.26-1chl1~precise1 state=installed update_cache=true
  sudo: yes

- name: Make a directory for wynno files
  file: path=/home/deploy/wynno state=directory

# Copy over the app code, the necessary config .json files, and install node modules
- include: copy_code.yml

- name: Install the Forever node module globally
  # This is necessary so that the Upstart script below finds Forever, which is what
  # actually runs the node process
  npm: name=forever global=yes
  sudo: yes

- name: Copy over the Upstart script which runs node via Forever
  template: src=wynno.conf.j2 dest=/etc/init/wynno.conf # not sure if mode=0644 is necessary or not
  sudo: yes

- name: Copy script to open up node_port for connections from nginxservers
  # Note we use a template file here so we can loop over all hosts in the nodeservers group
  # Otherwise we'd have to hardcode the names of the hosts to get the IPs for which we want to make ufw rules
  template: src=ufw_allow_nginx_servers.sh.j2 dest=/home/deploy/ufw_allow_nginx_servers.sh

- name: Execute that script to create the new ufw rules
  shell: sh ufw_allow_nginx_servers.sh

- name: Reload ufw to enable the new rules
  #ufw: state=reloaded
  command: ufw reload
  sudo: yes

- name: Reboot - which should start server thanks to Upstart script
  command: reboot
  sudo: yes

- name: Wait 2 minutes for server to boot up again
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} delay=120

- name: Check that node server is launched upon reboot
  command: sudo service wynno status
  register: wynno_status
  failed_when: "wynno_status.stdout.find('start/running') == -1"
