---
# This playbook is executed on all wynno production servers. It makes the virgin servers more secure.

- name: Change root password
  user: name=root password={{ root_password }}

- name: Update APT package cache
  apt: update_cache=yes

- name: Run apt-get upgrade
  apt: upgrade=yes

- name: Install fail2ban
  apt: pkg=fail2ban state=present

- name: Copy over my custom fail2ban config file
  # This file contains wynno-specific email address, ssh port, and activates email notifications
  copy: src=jail.local dest=/etc/fail2ban/jail.local
  notify: Restart fail2ban

- name: Add deployment user
  user: name=deploy password={{ deploy_password }}

- name: Add authorized deploy key
  # Note the public key is already on the VPS; it was put there by DO in the creation of the server
  # The task here just associates the key with the deploy user, so we don't have to SSH in as root
  authorized_key: user=deploy key="{{ item }}"
  with_file:
    - ../../../keys/{{ ansible_hostname }}.pub

- name: Remove sudo group rights
  lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Add deploy user to sudoers
  lineinfile: dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) ALL" state=present

- name: Copy over our custom SSH config file
  # Specifically our changes could have been specified vs. the default via the following lineinfile tasks:
  # Disallow root access
  # lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  # Change port from 22 to 202
  # lineinfile: dest=/etc/ssh/sshd_config regexp="^Port" line="Port 202" state=present
  # Disable password authentication
  # lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  # lineinfile: dest=/etc/ssh/sshd_config regexp="^ChallengeResponseAuthentication" line="ChallengeResponseAuthentication no" state=present
  # lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitEmptyPasswords" line="PermitEmptyPasswords no" state=present
  # Enable key-based auth
  # lineinfile: dest=/etc/ssh/sshd_config regexp="^PubkeyAuthentication" line="PubkeyAuthentication yes" state=present
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: Restart ssh

- name: Set default for ufw to deny all incoming connections
  command: ufw default deny incoming
  sudo: yes

- name: Set default for ufw to allow all outgoing connections
  command: ufw default allow outgoing
  sudo: yes

- name: Setup ufw to only allow incoming SSH connections
  # We allow connections only from the wynno-gateway AWS instance which has a permanent IP
  command: ufw allow proto tcp from {{ gateway_perm_ip }} port 202
  sudo: yes

- name: Enable ufw
  shell: echo 'y' | ufw enable
  sudo: yes

- name: Copy debconf selections so that Postfix can configure itself non-interactively
  copy: src=postfix_selections dest=/tmp/postfix_selections

- name: Set up Postfix to relay mail
  command: debconf-set-selections /tmp/postfix_selections

- name: Install logwatch
  apt: pkg=logwatch state=present

- name: Make logwatch mail {{ logwatch_email }} daily
  lineinfile: dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high" state=present create=yes

- name: Make the NODE_ENV environment variable a system-wide variable by adding simple shell script to /etc/profile.d
  template: src=set_env.sh.j2 dest=/etc/profile.d/set_env.sh

- name: Update ansible_ssh_port to the new SSH port for subsequent SSH connections
  set_fact: ansible_ssh_port={{ new_ssh_port }}
  # Cf. http://serverfault.com/questions/545978/how-to-handle-ssh-port-changes-with-ansible

# Possible additional steps:
# set time zone
# install tripwire
