---
# This playbook copies over the Python code run by our machine learning nodes.
# It is used by both the initial deployment playbook (site.yml) and in rolling
# upgrades of app code.

- name: Copy over the python.json file
  copy: src=../../../../../dist/lib/config/keys/prod/python.json dest=/home/deploy/dist/lib/config/keys/prod/python.json

- name: Copy over the Python files
  synchronize: src=../../../../../dist/lib/python dest=/home/deploy/dist/lib delete=yes
