---
# This playbook copies over the static assets served by nginx. It is used by both the
# initial deployment playbook (site.yml) and in rolling upgrades of app code.

- name: Copy over the folder of static assets that will be served by nginx
  synchronize: src=../../../../../dist/public dest=/home/deploy/wynno/dist
  # note we don't use the delete option with synchronize here because we want old app static files
  # to be capable of being served until all nodeservers have been updated to point to the new
  # app static files
  sudo: yes
  # sudo is crucial here because the deploy user loses write privileges on the folder
  # per the below steps, which have already been run by site.yml when this playbook
  # is used in a rolling upgrade
  # Note also that we could replace /home/deploy/wynno/dist/public with {{ root_path }}
  # later in this file but since we don't have a variable for the /home/deploy/wynno/dist
  # path used in this task, we won't make that variable substitution, just for the sake
  # of clarity

- name: Make the nginx_user the owner of this folder
  shell: chown -R {{ nginx_user }}:{{ nginx_user }} /home/deploy/wynno/dist/public
  sudo: yes

- name: Set read permissions on this folder
  shell: chmod -R 0755 /home/deploy/wynno/dist/public
  sudo: yes
