---
# This playbook copies over the static assets served by nginx. It is used by both the
# initial deployment playbook (site.yml) and in rolling upgrades of app code.

- name: Copy over the folder of static assets that will be served by nginx
  copy: src=../../../../../dist/public dest=/home/deploy/wynno/dist

- name: Make the nginx_user the owner of this folder
  shell: chown -R {{ nginx_user }}:{{ nginx_user }} /home/deploy/wynno/dist/public
  sudo: yes

- name: Set read permissions on this folder
  shell: chmod -R 0755 /home/deploy/wynno/dist/public
  sudo: yes
