---

- name: Copy over the folder of static assets that will be served by nginx
  copy: src=../../../../../dist/public dest=/home/deploy/wynno/dist/public

- name: Open up port 80 to connections from all IP addresses since this is our public-facing web server
  command: ufw allow 80/tcp
  sudo: yes

- name: Open up port 443 to connections from all IP adddresses for same reason
  command: ufw allow 443/tcp
  sudo: yes

- name: Reload ufw to enable the new settings
  command: ufw reload
  sudo: yes

- name: Add nginx PPA
  shell: add-apt-repository ppa:nginx/stable
  sudo: yes

- name: Update APT package cache
  apt: update_cache=yes

- name: Install nginx
  apt: pkg=nginx state=installed update_cache=true
  notify:
    - Start nginx

- name: Set nginx to start on boot
  command: update-rc.d nginx defaults # Cf. https://www.digitalocean.com/community/articles/how-to-install-nginx-on-ubuntu-12-04-lts-precise-pangolin

- name: Copy over the SSL .pem credential
  copy: src=www_wynno_com.pem dest=/etc/nginx/ssl/www_wynno_com.pem

- name: Copy over SSL .key credential
  copy: src=www_wynno_com.key dest=/etc/nginx/ssl/www_wynno_com.key

- name: Make a copy of the default nginx.conf file if such copy does not already exist
  command: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.default creates=/etc/nginx/nginx.conf.default

- name: Replace nginx.conf with the one for wynno
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644 # or try 0755 if there is nginx error
  notify:
    - Restart nginx
