---
- hosts: newnginx
  remote_user: deploy

  tasks:
  - name: Set the NODE_ENV environment variable to 'prod'
    shell: export NODE_ENV=prod

  - name: Copy over the folder of static assets that will be served by nginx
    copy: src=../../../dist/public dest=/home/deploy/wynno/dist/public

  - name: Open up port 80
    shell: ufw allow 80/tcp
 
  - name: Open up port 443
    shell: ufw allow 443/tcp

  # before installing nginx, update the version of nginx that gets installed by apt?

  - name: Install nginx
    apt: pkg=nginx state=installed update_cache=true
    notify:
      - start nginx

  - name: Copy over the SSL certificate
    copy: src=www_wynno_com.pem dest=/etc/nginx/ssl/www_wynno_com.pem
    copy: src=www_wynno_com.key dest=/etc/nginx/ssl/www_wynno_com.key

  - name: Replace default nginx.conf with the one for wynno
    copy: src=nginx.conf dest=/etc/nginx mode=0644 # or try 0755 if there is nginx error
    notify:
      - restart nginx

  handlers:
  - name: start nginx
    service: name=nginx state=started
  - name: restart nginx
    service: name=nginx state=restarted
